version: '3'

services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: observote
      MYSQL_USER: root
      MYSQL_PASSWORD:
